statusURL=https://ews-esz-emea.api.bosch.com/workflow/workon02emea/q/v1/status/
keyId=82eef6eb-5cb1-4ea3-a685-bc750be13748
host=ews-esz-emea.api.bosch.com
createRequestURL=https://ews-esz-emea.api.bosch.com/workflow/workon02emea/q/v1/createrequest/create
contentType=application/json

status=Unresolved
workflowLink=https://rb-wam-q.bosch.com/workon01/workflow02q/browse/
Success=Success
profile.name=test
locale=en_UK

defaultChangesetURL=https://rb-cubezone-q.de.bosch.com/epcui/changesets/
 
spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mysql://rb-cubezone-q.de.bosch.com:3306/epc?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=topsecret
#spring.datasource.url=jdbc:mysql://si0vmc2209.de.bosch.com:3306/epc?useSSL=false
spring.datasource.url=jdbc:mysql://bp0vm025.emea.bosch.com:3306/epc?useSSL=false
spring.datasource.username=tooldatabase
spring.datasource.password=tooldatabase

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Hibernate SQL logs
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Enable Hibernate second-level cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true

# Use JCache (Ehcache 3)
# Tells Hibernate which cache region factory to use for 2nd-level cache.
spring.jpa.properties.hibernate.cache.region.factory_class=jcache
# Defines which JCache provider Hibernate should use for 2nd-level cachin
spring.jpa.properties.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.javax.cache.uri=classpath:ehcache.xml
# Controls how JPA/Hibernate uses the 2nd-level cache for entities.
spring.jpa.properties.javax.persistence.sharedCache.mode=ENABLE_SELECTIVE

# TEU Tool Properties
TEU_TOOL_PATH_SPEC = D:\\Cubezone_Tools\\TEU_TOOL\\templates\\?ProjAreaName\\template\\specification.xml
TEU_TOOL_PROPERTIES_PATH = D:\\Cubezone_Tools\\TEU_TOOL\\software\\com.bosch.rtc.utils.templateexchange\\epcToolTemplate.properties
TEU_TOOL_Templates_PATH = D:\\Cubezone_Tools\\TEU_TOOL\\templates\\?ProjAreaName\\
TEU_CMD_ARGS_1 = cmd.exe
TEU_CMD_ARGS_2 = /c
TEU_CMD_ARGS_3 = java -jar "D:\\Cubezone_Tools\\TEU_TOOL\\software\\com.bosch.rtc.utils.templateexchange\\com.bosch.rtc.utils.templateexchange-2019.2.0.jar" -c "D:\\Cubezone_Tools\\TEU_TOOL\\software\\com.bosch.rtc.utils.templateexchange\\epcToolTemplate.properties" -p "?ProjAreaName" -t ed
TEU_CMD_ARGS_4 = java -jar "D:\\Cubezone_Tools\\TEU_TOOL\\software\\com.bosch.rtc.utils.templateexchange\\com.bosch.rtc.utils.templateexchange-2019.2.0.jar" -c "D:\\Cubezone_Tools\\TEU_TOOL\\software\\com.bosch.rtc.utils.templateexchange\\epcToolTemplate.properties" -p "?ProjAreaName" -t au

#Transform properties
PRECON_READONLY_DESC = Verifies that a work item that matches a condition can only be saved if the selected attributes are unchanged
PRECON_READONLY_NAME = Read-Only Attributes For Condition
PRECON_READONLY_ID = com.ibm.team.workitem.advisor.readOnlyAttributes
PRECON_REQ_DESC = Verifies that a work item that matches a condition can only be saved if the selected attributes are different from the default value
PRECON_REQ_NAME = Required Attributes For Condition
PRECON_REQ_ID = com.ibm.team.workitem.advisor.requiredAttributes

#ALM properties
ALM_TEST_USER_NAME = res131aesi
ALM_TEST_USER_PASSWORD = CI#rtc6069_Jenkins
ALM_REPOSITORY_URL = https://rb-alm-03-q.de.bosch.com/ccm
ALM_SERVICE_USER_NAME = ccj2st



#Swagger Properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.filter = false
springdoc.swagger-ui.syntaxHighlight.activated = false


#Scheduler cron expression second (0-59) minute (0 - 59) hour (0 - 23) day of the month (1 - 31) month (1 - 12) (or JAN-DEC) day of the week (0 - 7)
cronExpToProcessRequest= 0 0 1 ? * MON-FRI
cronExpToSyncELMData= 0 0 1 ? * MON-FRI
cronExpToSyncWorkONStatus= 0 0 1 ? * MON-FRI



# Default session timeout (in seconds)
server.servlet.session.timeout=600
LOGGED_IN_USER = LOGGED_IN_USER

#spring.aop.auto=false

LADAP_USERNAME = DE\\CCJ2ST
LADAP_PASSWORD = jp2;sL,Wt